sudo: required
services:
  - docker

before_install:
  - docker build -t kdevelop/docker_react -f Dockerfile.dev .
  
script:
  #- docker run kdevelop/docker_react npm run test -- -- coverage
  - docker run -e CI=true kdevelop/docker_react npm run test

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-186914641285"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: "AKIASXBH3CWC37YVSDWX" #$AWS_SECRET_KEY_BIS #AWS_ACCESS_KEY
  secret_access_key: "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"
    #secure: #$AWS_ACCESS_KEY_BIS  #$AWS_SECRET_KEY
